In [1]:
#!pip install opencv-python

In [2]:
import numpy as np
import cv2

In [3]:
img = cv2.imread('imagens/lena.png', 0)

In [4]:
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
cv2.imwrite('imagens/lena_gray.png', img)

True

In [6]:
img = cv2.imread('imagens/lena.png')

print(img.shape)
px = img[50,50]
print(px)

(512, 512, 3)
[114 140 230]


O Open CV acessa o canal de imagens no padrão BGR (Blue Green Red)

## Acessando canais

Acessando o canal blue

In [7]:
blue = img[50, 50, 0] # -> os dois primeiros campos (50, 50) é a posiçao do pixel o terceiro campo do vetor (0) é o canal
print(blue)

114


Acessando o canal Red

In [8]:
red = img[50, 50, 2]
print(red)

230


Acessando o canal green

In [9]:
green = img[50, 50, 1]
print(green)

140


Mudando o valor de um unico pixel

In [10]:
img[50,50] = [255, 255, 255] # branco
print(img[50,50])

[255 255 255]


Forma otimizada de acessar pixel de uma imgem usando numpy

In [11]:
red = img.item(50, 50, 2)
print(red)

255


Modificando a intensidade do cancl Red do pixel usando numpy

In [12]:
img.itemset((50,50,2), 100)
red = img.item(50, 50, 2)
print(red)

100


Retornando uma tupla de linha, coluna e numero de canais de cores da imagem

In [13]:
print(img.shape)

(512, 512, 3)


Retorna o numero de pixel

In [14]:
print(img.size)

786432


Imprimindo apenas o canal red

In [15]:
*_, r = cv2.split(img)
print(r)

[[226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 ...
 [ 84  84  92 ... 173 172 177]
 [ 82  82  96 ... 179 181 185]
 [ 82  82  96 ... 179 181 185]]


Modificando apenas o canal Red para 0

In [16]:
img[:,:,2] = 0
cv2.imwrite('imagens/lena_red.png',img)

True

## Redimensionamento

Rotacionando a imagem em 180 graus

In [17]:
#!pip install imutils

In [18]:
import imutils

In [19]:
img = imutils.rotate(img, 180)

In [20]:
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Redimensionamento e Imagens

In [21]:
img = cv2.imread('imagens/lena.png')

In [22]:
resized = cv2.resize(img, (720, 720), interpolation=cv2.INTER_CUBIC)
cv2.imshow('', resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Função de desenho

Desenhando uma linha

Para desenhar uma linha, você precisa passar as coordenadas iniciais e finais da linha

Criand uma imagem preta e desenhando uma linha azul no canto superior esquerdo e inferior direito

In [23]:
# Cria uma imagem preta
img = np.zeros((512, 512, 3), np.uint8)

# Desenha uma linha diagonal azul com expessura de 5 px
img = cv2.line(img, (0, 0), (511, 511), (255, 0, 0), 1)

cv2.imshow('', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Desehando um retangulo

Especificamos o canto superior esquerdo e o canto inferior direito do retangulo

In [24]:
img = cv2.rectangle(img, (384, 0), (510, 128), (0, 255, 0), 3)

cv2.imshow(None, img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Adicionando texto em uma imagem

In [25]:
img = np.zeros((512, 512, 3), np.uint8)

font = cv2.FONT_HERSHEY_DUPLEX
cv2.putText(img, 'OpenCV', (10, 500), font, 4, (255, 255, 255), 2, cv2.LINE_AA)

cv2.imshow(None, img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Operação sobre Vídeo

In [26]:
from os import path, makedirs

In [27]:
frames_dir = 'imagens/frame_dir/'

if not path.exists(frames_dir):
    makedirs(frames_dir)

In [28]:
cap = cv2.VideoCapture('dataset/video.mp4') 

amount_of_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT )

frame_second = 30
frames = amount_of_frames // frame_second 

for i in range(0, int(frames)):
    cap.set(cv2.CAP_PROP_POS_FRAMES, i * frame_second)
    ret, frame = cap.read()

    file_frame = path.join(frames_dir, f'frame_{i}.png')
    cv2.imwrite(file_frame, frame)

cap.release()

**Referências**

[OpenCV-Python Tutorials](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_tutorials.html)